#!/bin/sh
#
# fluxbox startup-script:

start_nitrogen () {
  sleep 2
  exec nitrogen --restore
}

start_redshift () {
  sleep 2
  exec redshift -l 47:9
}

start_conky () {
  sleep 2
  exec /usr/bin/conky
}

# Change your keymap:
#setxkbmap -layout de,de -variant neo,basic -option -option grp:sclk_toggle -option grp_led:scroll
setxkbmap de neo

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
export GDK_NATIVE_WINDOWS=true

exec pulseaudio &
exec ~/.screenlayout/screens.sh &
exec /usr/bin/tilda &
exec transmission-gtk &
exec /usr/bin/tint2 &
exec dropbox &
start_nitrogen &
start_conky &
start_redshift &
exec /usr/lib/notification-daemon-1.0/notification-daemon &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/tmp/fluxbox.log"
